machouille_produit:
    resource: "@MachouilleProduitBundle/Resources/config/routing.yml"
    prefix:   /

machouille_portail:
    resource: "@MachouilleLoginBundle/Resources/config/routing.yml"
    prefix:   /
